### ISSUE TITLE
npm errors

### ISSUE THREAD

**Issue by PortPixel** [huytd/lit-demo#1]
C:\Users\xxx\Downloads\lit-demo-master\lit-demo-master>npm install
npm WARN package.json lit-js-demo@1.0.0 No repository field.
express@4.14.0 node_modules\express
├── escape-html@1.0.3
├── encodeurl@1.0.1
├── cookie-signature@1.0.6
├── content-type@1.0.2
├── merge-descriptors@1.0.1
├── methods@1.1.2
├── vary@1.1.0
├── range-parser@1.2.0
├── etag@1.7.0
├── parseurl@1.3.1
├── serve-static@1.11.1
├── array-flatten@1.1.1
├── utils-merge@1.0.0
├── content-disposition@0.5.1
├── fresh@0.3.0
├── path-to-regexp@0.1.7
├── cookie@0.3.1
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.12)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.12)
└── send@0.14.1 (destroy@1.0.4, ms@0.7.1, statuses@1.3.0, mime@1.3.4, http-error
s@1.5.0)

engine.io@1.7.0 node_modules\engine.io
├── base64id@0.1.0
├── debug@2.2.0 (ms@0.7.1)
├── ws@1.1.1 (options@0.0.6, ultron@1.0.2)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.12)
└── engine.io-parser@1.3.0 (wtf-8@1.0.0, arraybuffer.slice@0.0.6, base64-arraybu
ffer@0.1.5, blob@0.0.4, after@0.8.1, has-binary@0.1.6)

C:\Users\xxx\Downloads\lit-demo-master\lit-demo-master>npm start

> lit-js-demo@1.0.0 start C:\Users\xxx\Downloads\lit-demo-master\lit-demo-maste
> r
> node main.js

Server is listening on port 3000
Client Jq90d-Jc_rdco4S9AAAA connected!
Total: 1
C:\Users\xxx\Downloads\lit-demo-master\lit-demo-master\clients.js:30
            global.SOCKET_CLIENTS[id].send(Buffer.from(JSON.stringify({ event: e
ventName, message: data })));
                                                  ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.emit (C:\Users\xxx\Downloads\lit-demo-master\lit-demo-master\clie
nts.js:30:51)
    at Object.connection (C:\Users\xxx\Downloads\lit-demo-master\lit-demo-maste
r\game\server.js:93:16)
    at Server.<anonymous> (C:\Users\xxx\Downloads\lit-demo-master\lit-demo-mast
er\main.js:18:9)
    at emitOne (events.js:77:13)
    at Server.emit (events.js:169:7)
    at Server.handshake (C:\Users\xxx\Downloads\lit-demo-master\lit-demo-master
\node_modules\engine.io\lib\server.js:312:8)
    at C:\Users\xxx\Downloads\lit-demo-master\lit-demo-master\node_modules\engi
ne.io\lib\server.js:216:12
    at Server.verify (C:\Users\xxx\Downloads\lit-demo-master\lit-demo-master\no
de_modules\engine.io\lib\server.js:156:36)
    at Server.handleRequest (C:\Users\xxx\Downloads\lit-demo-master\lit-demo-ma
ster\node_modules\engine.io\lib\server.js:206:8)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! lit-js-demo@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lit-js-demo@1.0.0 start script 'node main.js'.
npm ERR! This is most likely a problem with the lit-js-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lit-js-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls lit-js-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxx\Downloads\lit-demo-master\lit-demo-master\npm-debug.l
og

**Comment by huytd** [comment]
Thanks, I will check it
